# Generated by Django 4.1.7 on 2023-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default='Something'),
        ),
    ]
