# Generated by Django 4.1.7 on 2023-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0003_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=12)),
                ('DOB', models.CharField(max_length=50)),
                ('selectmembershipplan', models.CharField(max_length=12)),
                ('selecttrainer', models.CharField(max_length=12)),
                ('reference', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('gender', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=12)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
    ]
