# Generated by Django 4.1.7 on 2023-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0004_enrollment_membershipplan_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
    ]
