# Generated by Django 4.1.7 on 2023-06-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
