# Generated by Django 4.1.7 on 2023-06-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_alter_enrollment_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='fullname',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='reference',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='selectmembershipplan',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='selecttrainer',
            field=models.CharField(max_length=55),
        ),
    ]
