# Generated by Django 4.1.7 on 2023-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0007_alter_enrollment_fullname_alter_enrollment_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Something', max_length=100),
        ),
    ]
