# Generated by Django 4.1.7 on 2023-06-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0008_rename_description_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Gallery')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
