# Generated by Django 4.1.7 on 2023-06-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=100)),
                ('logout', models.CharField(max_length=100)),
                ('workout', models.CharField(max_length=100)),
                ('trainedby', models.CharField(max_length=100)),
            ],
        ),
    ]
