# Generated by Django 4.1.7 on 2023-06-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0010_attendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='timestamp',
            new_name='selectdate',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='workout',
            new_name='selectworkout',
        ),
    ]
