# Generated by Django 4.1.7 on 2023-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0011_rename_timestamp_attendence_selectdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='phone',
        ),
        migrations.AddField(
            model_name='attendence',
            name='phonenumber',
            field=models.CharField(default='Something', max_length=15),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phonenumber',
            field=models.CharField(default='Something', max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
