# Generated by Django 4.1.7 on 2023-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0012_remove_trainer_phone_attendence_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
