# Generated by Django 4.1.7 on 2023-06-26 17:31

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0013_alter_attendence_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
    ]
